@ECHO OFF

SET SERVER=WINTERMUTE
SET DATABASE=USTTI
SET USERNAME=USTTIWEBMGR
SET PASSWORD=USTTIWEB2006

OSQL -S %SERVER% -E -i views.sql

OSQL -S %SERVER% -E -i procedures.sql

OSQL -S %SERVER% -E -i grant.sql