USE [USTTI]

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_DEFAULT TO USTTIWEBMGR
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_COURSES TO USTTIWEBMGR
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_COUNTRIES TO USTTIWEBMGR
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_FUNDERS TO USTTIWEBMGR
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_SPONSORS TO USTTIWEBMGR
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_STATUS TO USTTIWEBMGR
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_STUDENT_EXTENDED TO USTTIWEBMGR
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON AD_HOC_STUDENT_BASIC TO USTTIWEBMGR
GO

GRANT EXEC ON sp_StudentSheet TO USTTIWEBMGR
GO

GRANT EXEC ON sp_CourseSheet TO USTTIWEBMGR
GO

GRANT EXEC ON spFundingSheet TO USTTIWEBMGR
GO

GRANT EXEC ON sp_ParticipantByCourse TO USTTIWEBMGR
GO

GRANT EXEC ON sp_ParticipantByCountry TO USTTIWEBMGR
GO

GRANT EXEC ON sp_TrainingFactSheet TO USTTIWEBMGR
GO

GRANT EXEC ON sp_TrainingCourseFactSheet TO USTTIWEBMGR
GO

GRANT EXEC ON sp_CoursesBySponsor TO USTTIWEBMGR
GO 

GRANT EXEC ON sp_MultiBioSheet TO USTTIWEBMGR
GO

GRANT EXEC ON sp_MultiBioSheetStatus TO USTTIWEBMGR
GO



